-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\wickh\Documents\NIH\simulink_models\models\fft_filters\hdlsrc\fft_filters\fft_filters_FIFO_Write_Select_block.vhd
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fft_filters_FIFO_Write_Select_block
-- Source Path: fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_Write_Select
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY fft_filters_FIFO_Write_Select_block IS
  PORT( fifo_counter                      :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        valid_signal                      :   IN    std_logic;
        valid_1                           :   OUT   std_logic;
        valid_2                           :   OUT   std_logic;
        valid_3                           :   OUT   std_logic;
        valid_4                           :   OUT   std_logic
        );
END fft_filters_FIFO_Write_Select_block;


ARCHITECTURE rtl OF fft_filters_FIFO_Write_Select_block IS

  ATTRIBUTE multstyle : string;

  -- Signals
  SIGNAL fifo_counter_unsigned            : unsigned(1 DOWNTO 0);  -- ufix2

BEGIN
  fifo_counter_unsigned <= unsigned(fifo_counter);

  FIFO_Write_Select_output : PROCESS (fifo_counter_unsigned, valid_signal)
  BEGIN
    CASE fifo_counter_unsigned IS
      WHEN "00" =>
        valid_1 <= valid_signal;
        valid_2 <= '0';
        valid_3 <= '0';
        valid_4 <= '0';
      WHEN "01" =>
        valid_1 <= '0';
        valid_2 <= valid_signal;
        valid_3 <= '0';
        valid_4 <= '0';
      WHEN "10" =>
        valid_1 <= '0';
        valid_2 <= '0';
        valid_3 <= valid_signal;
        valid_4 <= '0';
      WHEN "11" =>
        valid_1 <= '0';
        valid_2 <= '0';
        valid_3 <= '0';
        valid_4 <= valid_signal;
      WHEN OTHERS => 
        valid_1 <= '0';
        valid_2 <= '0';
        valid_3 <= '0';
        valid_4 <= '0';
    END CASE;
  END PROCESS FIFO_Write_Select_output;


END rtl;

