pipeline
{
    agent none
    stages
    {
        stage ('Ubuntu 20.04')
        {
            agent {label 'Ubuntu_20.04.1'}
            stages 
            {
                stage('Clone Frost Linux-SoCFPGA Repo')
                {
                    steps
                    {
                        sh 'git clone https://github.com/fpga-open-speech-tools/linux-socfpga.git;'
                    }
                }
                stage('Configure Linux Kernel Build Env.')
                {
                    steps
                    {   dir("linux-socfpga")
                        {
                            sh 'make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- openspeech_defconfig;'
                            sh 'make prepare ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-;'
                        }
                    }
                }
                stage('Build LKMs')
                {
                    parallel
                    {
                        stage('AD1939 LKM')
                        {
                            steps
                            {   dir("ad1939")
                                {   
                                    sh 'make;'
                                    archiveArtifacts artifacts: '*.ko', fingerprint: true 
                                }
                            }
                        }
                        stage('AD7768 LKM')
                        {
                            steps
                            {   dir("ad7768")
                                {
                                    sh 'make;'
                                    archiveArtifacts artifacts: '*.ko', fingerprint: true 
                                }
                            }
                        }
                        stage('PGA2505 LKM')
                        {
                            steps
                            {   dir("pga2505")
                                {
                                    sh 'make;'
                                    archiveArtifacts artifacts: '*.ko', fingerprint: true 
                                }
                            }
                        }
                        stage('TPA6160A2 LKM')
                        {
                            steps
                            {   dir("tpa613a2")
                                {
                                    sh 'make;'
                                    archiveArtifacts artifacts: '*.ko', fingerprint: true 
                                }
                            }
                        }
                    }
                }
                stage('Cleanup')
                {
                    deleteDir()
                    dir("${workspace}@tmp") {
                        deleteDir()
                    }
                } 
            }
        }
    }
}