pipeline
{
    agent none
    stages
    {
        stage ('Ubuntu 20.04')
        {
            agent {label 'Ubuntu_20.04.1'}
            stages 
            {
                stage ('Is this empty?')
                {
                    steps
                    {
                        sh 'ls -al'
                    }
                    
                }
                stage('Clone Frost Linux-SoCFPGA Repo')
                {
                    steps
                    {
                        sh 'echo "git clone https://github.com/fpga-open-speech-tools/linux-socfpga.git;"'
                    }
                }
                stage('Configure Linux Kernel Build Env.')
                {
                    steps
                    {   dir("linux-socfpga")
                        {
                            sh 'echo "make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- openspeech_defconfig;"'
                            sh 'echo "make prepare ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-;"'
                        }
                    }
                }
                stage('Build LKMs')
                {
                    parallel
                    {
                        stage('AD1939 LKM')
                        {
                            steps
                            {   dir("ad1939")
                                {   sh 'ls -al'
                                    sh 'pwd;'
                                    sh 'ls -al ..'
                                    sh 'make;'
                                    archiveArtifacts artifacts: '*.ko', fingerprint: true 
                                }
                            }
                        }
                        stage('AD7768 LKM')
                        {
                            steps
                            {   dir("ad7768")
                                {
                                    sh 'make;'
                                    archiveArtifacts artifacts: '*.ko', fingerprint: true 
                                }
                            }
                        }
                        stage('PGA2505 LKM')
                        {
                            steps
                            {   dir("pga2505")
                                {
                                    sh 'make;'
                                    archiveArtifacts artifacts: '*.ko', fingerprint: true 
                                }
                            }
                        }
                        stage('TPA6160A2 LKM')
                        {
                            steps
                            {   dir("tpa613a2")
                                {
                                    sh 'make;'
                                    archiveArtifacts artifacts: '*.ko', fingerprint: true 
                                }
                            }
                        }
                        stage('Cleanup')
                        {
                            steps
                            {
                                deleteDir()
                                dir("${workspace}@tmp") {
                                    deleteDir()
                                }
                            }
                        } 
                    }
                }
            }
        }
    }
}