# TCL File Generated by Component Editor 18.0
# Tue Nov 05 12:52:42 MST 2019
# DO NOT MODIFY


# 
# FE_I2S_M9K "FE_I2S_M9K" v1.0
#  2019.11.05.12:52:42
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module FE_I2S_M9K
# 
set_module_property DESCRIPTION ""
set_module_property NAME FE_I2S_M9K
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME FE_I2S_M9K
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL FE_I2S_M9K
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FE_I2S_M9K.vhd VHDL PATH FE_I2S_M9K.vhd TOP_LEVEL_FILE
add_fileset_file Gen_Shift_Container.vhd VHDL PATH Gen_Shift_Container.vhd
add_fileset_file I2S_DPR_M9K.qip OTHER PATH I2S_DPR_M9K.qip


# 
# parameters
# 
add_parameter bclk_div STRING 00000100
set_parameter_property bclk_div DEFAULT_VALUE 00000100
set_parameter_property bclk_div DISPLAY_NAME bclk_div
set_parameter_property bclk_div TYPE STRING
set_parameter_property bclk_div UNITS None
set_parameter_property bclk_div HDL_PARAMETER true
add_parameter lrclk_div STRING 00010000
set_parameter_property lrclk_div DEFAULT_VALUE 00010000
set_parameter_property lrclk_div DISPLAY_NAME lrclk_div
set_parameter_property lrclk_div TYPE STRING
set_parameter_property lrclk_div UNITS None
set_parameter_property lrclk_div HDL_PARAMETER true
add_parameter n_drivers STRING 00000010
set_parameter_property n_drivers DEFAULT_VALUE 00000010
set_parameter_property n_drivers DISPLAY_NAME n_drivers
set_parameter_property n_drivers TYPE STRING
set_parameter_property n_drivers UNITS None
set_parameter_property n_drivers HDL_PARAMETER true
add_parameter max_drivers INTEGER 32
set_parameter_property max_drivers DEFAULT_VALUE 32
set_parameter_property max_drivers DISPLAY_NAME max_drivers
set_parameter_property max_drivers TYPE INTEGER
set_parameter_property max_drivers UNITS None
set_parameter_property max_drivers ALLOWED_RANGES -2147483648:2147483647
set_parameter_property max_drivers HDL_PARAMETER true
add_parameter read_ahead INTEGER 1
set_parameter_property read_ahead DEFAULT_VALUE 1
set_parameter_property read_ahead DISPLAY_NAME read_ahead
set_parameter_property read_ahead TYPE INTEGER
set_parameter_property read_ahead UNITS None
set_parameter_property read_ahead ALLOWED_RANGES -2147483648:2147483647
set_parameter_property read_ahead HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock sys_clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point data_input
# 
add_interface data_input avalon_streaming end
set_interface_property data_input associatedClock sys_clk
set_interface_property data_input associatedReset reset
set_interface_property data_input dataBitsPerSymbol 32
set_interface_property data_input errorDescriptor ""
set_interface_property data_input firstSymbolInHighOrderBits true
set_interface_property data_input maxChannel 0
set_interface_property data_input readyLatency 0
set_interface_property data_input ENABLED true
set_interface_property data_input EXPORT_OF ""
set_interface_property data_input PORT_NAME_MAP ""
set_interface_property data_input CMSIS_SVD_VARIABLES ""
set_interface_property data_input SVD_ADDRESS_GROUP ""

add_interface_port data_input data_input_channel channel Input 7
add_interface_port data_input data_input_data data Input 32
add_interface_port data_input data_input_error error Input 2
add_interface_port data_input data_input_valid valid Input 1


# 
# connection point i2s_output
# 
add_interface i2s_output conduit end
set_interface_property i2s_output associatedClock ""
set_interface_property i2s_output associatedReset ""
set_interface_property i2s_output ENABLED true
set_interface_property i2s_output EXPORT_OF ""
set_interface_property i2s_output PORT_NAME_MAP ""
set_interface_property i2s_output CMSIS_SVD_VARIABLES ""
set_interface_property i2s_output SVD_ADDRESS_GROUP ""

add_interface_port i2s_output bclk_out bclk_out Output 1
add_interface_port i2s_output lrclk_out lrclk_out Output 1
add_interface_port i2s_output sdata_out sdata_out Output max_drivers


# 
# connection point sys_clk
# 
add_interface sys_clk clock end
set_interface_property sys_clk clockRate 0
set_interface_property sys_clk ENABLED true
set_interface_property sys_clk EXPORT_OF ""
set_interface_property sys_clk PORT_NAME_MAP ""
set_interface_property sys_clk CMSIS_SVD_VARIABLES ""
set_interface_property sys_clk SVD_ADDRESS_GROUP ""

add_interface_port sys_clk sys_clk clk Input 1


# 
# connection point mclk
# 
add_interface mclk clock end
set_interface_property mclk clockRate 0
set_interface_property mclk ENABLED true
set_interface_property mclk EXPORT_OF ""
set_interface_property mclk PORT_NAME_MAP ""
set_interface_property mclk CMSIS_SVD_VARIABLES ""
set_interface_property mclk SVD_ADDRESS_GROUP ""

add_interface_port mclk mclk_in clk Input 1

