-- -------------------------------------------------------------
-- 
-- File Name: D:\NIH3Repo\simulink_models\models\delay_and_sum_beamformer\hdlsrc\DSBF\DSBF_normalize_shift.vhd
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DSBF_normalize_shift
-- Source Path: DSBF/dataplane/Avalon Data Processing/normalize/normalize_shift
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY DSBF_normalize_shift IS
  PORT( input                             :   IN    std_logic_vector(35 DOWNTO 0);  -- sfix36_En28
        normalized                        :   OUT   std_logic_vector(35 DOWNTO 0)  -- sfix36_En28
        );
END DSBF_normalize_shift;


ARCHITECTURE rtl OF DSBF_normalize_shift IS

  ATTRIBUTE multstyle : string;

  -- Signals
  SIGNAL input_signed                     : signed(35 DOWNTO 0);  -- sfix36_En28
  SIGNAL normalized_tmp                   : signed(35 DOWNTO 0);  -- sfix36_En28

BEGIN
  input_signed <= signed(input);

  --MATLAB Function 'dataplane/Avalon Data Processing/normalize/normalize_shift': '<S34>:1'
  -- NOTE: we should be normalizing to +/- 1 with the following commented line,
  -- but the AD1939 VHDL expects +/- 0.5 normalization; so for now, I'm 
  -- normalizing to +/- 0.5 until we fix the VHDL
  --excessIntegerBits = input.WordLength - input.FractionLength - 1;
  --'<S34>:1:8'
  normalized_tmp <= SHIFT_RIGHT(input_signed, 8);

  normalized <= std_logic_vector(normalized_tmp);

END rtl;

