-- Parallel2Serial_32bits.vhd

-- Generated using ACDS version 18.0 614

library IEEE;
library Parallel2Serial_32bits_lpm_shiftreg_180;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use Parallel2Serial_32bits_lpm_shiftreg_180.Parallel2Serial_32bits_pkg.all;

entity Parallel2Serial_32bits is
	port (
		clock    : in  std_logic                     := '0';             --  lpm_shiftreg_input.clock
		load     : in  std_logic                     := '0';             --                    .load
		data     : in  std_logic_vector(31 downto 0) := (others => '0'); --                    .data
		shiftout : out std_logic                                         -- lpm_shiftreg_output.shiftout
	);
end entity Parallel2Serial_32bits;

architecture rtl of Parallel2Serial_32bits is
begin

	parallel2serial_32bits : component Parallel2Serial_32bits_lpm_shiftreg_180.Parallel2Serial_32bits_pkg.Parallel2Serial_32bits_lpm_shiftreg_180_wxh4spi
		port map (
			clock    => clock,    --  lpm_shiftreg_input.clock
			load     => load,     --                    .load
			data     => data,     --                    .data
			shiftout => shiftout  -- lpm_shiftreg_output.shiftout
		);

end architecture rtl; -- of Parallel2Serial_32bits
