# TCL File Generated by Component Editor 18.0
# Thu Mar 26 15:37:41 MDT 2020
# DO NOT MODIFY


# 
# mono2stereo_adapter "Mono to stereo streaming adapter" v1.0
# Trevor Vannoy 2020.03.26.15:37:41
# Convert a mono TDM data stream into a stereo TDM data stream
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module mono2stereo_adapter
# 
set_module_property DESCRIPTION "Convert a mono TDM data stream into a stereo TDM data stream"
set_module_property NAME mono2stereo_adapter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Trevor Vannoy"
set_module_property DISPLAY_NAME "Mono to stereo streaming adapter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mono2stereo_adapter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mono2stereo_adapter.vhd VHDL PATH mono2stereo_adapter.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter sample_rate NATURAL 48000 ""
set_parameter_property sample_rate DEFAULT_VALUE 48000
set_parameter_property sample_rate DISPLAY_NAME sample_rate
set_parameter_property sample_rate WIDTH ""
set_parameter_property sample_rate TYPE NATURAL
set_parameter_property sample_rate UNITS None
set_parameter_property sample_rate ALLOWED_RANGES 0:2147483647
set_parameter_property sample_rate DESCRIPTION ""
set_parameter_property sample_rate HDL_PARAMETER true
add_parameter clk_freq NATURAL 98304000 ""
set_parameter_property clk_freq DEFAULT_VALUE 98304000
set_parameter_property clk_freq DISPLAY_NAME clk_freq
set_parameter_property clk_freq WIDTH ""
set_parameter_property clk_freq TYPE NATURAL
set_parameter_property clk_freq UNITS None
set_parameter_property clk_freq ALLOWED_RANGES 0:2147483647
set_parameter_property clk_freq DESCRIPTION ""
set_parameter_property clk_freq HDL_PARAMETER true
add_parameter data_width NATURAL 32 ""
set_parameter_property data_width DEFAULT_VALUE 32
set_parameter_property data_width DISPLAY_NAME data_width
set_parameter_property data_width WIDTH ""
set_parameter_property data_width TYPE NATURAL
set_parameter_property data_width UNITS None
set_parameter_property data_width ALLOWED_RANGES 0:2147483647
set_parameter_property data_width DESCRIPTION ""
set_parameter_property data_width HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point data_out
# 
add_interface data_out avalon_streaming start
set_interface_property data_out associatedClock clock
set_interface_property data_out associatedReset reset
set_interface_property data_out dataBitsPerSymbol 32
set_interface_property data_out errorDescriptor ""
set_interface_property data_out firstSymbolInHighOrderBits true
set_interface_property data_out maxChannel 1
set_interface_property data_out readyLatency 0
set_interface_property data_out ENABLED true
set_interface_property data_out EXPORT_OF ""
set_interface_property data_out PORT_NAME_MAP ""
set_interface_property data_out CMSIS_SVD_VARIABLES ""
set_interface_property data_out SVD_ADDRESS_GROUP ""

add_interface_port data_out channel_out channel Output 1
add_interface_port data_out data_out data Output data_width
add_interface_port data_out valid_out valid Output 1


# 
# connection point data_in
# 
add_interface data_in avalon_streaming end
set_interface_property data_in associatedClock clock
set_interface_property data_in associatedReset reset
set_interface_property data_in dataBitsPerSymbol 32
set_interface_property data_in errorDescriptor ""
set_interface_property data_in firstSymbolInHighOrderBits true
set_interface_property data_in maxChannel 0
set_interface_property data_in readyLatency 0
set_interface_property data_in ENABLED true
set_interface_property data_in EXPORT_OF ""
set_interface_property data_in PORT_NAME_MAP ""
set_interface_property data_in CMSIS_SVD_VARIABLES ""
set_interface_property data_in SVD_ADDRESS_GROUP ""

add_interface_port data_in channel_in channel Input 1
add_interface_port data_in data_in data Input data_width
add_interface_port data_in valid_in valid Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst reset Input 1

