# TCL File Generated by Component Editor 18.0
# Mon Nov 05 11:32:48 MST 2018
# DO NOT MODIFY


# 
# FE_LR_To_Multichannel_Output "FE_LR_To_Multichannel_Output" v1.0
#  2018.11.05.11:32:48
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module FE_LR_To_Multichannel_Output
# 
set_module_property DESCRIPTION ""
set_module_property NAME FE_LR_To_Multichannel_Output
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME FE_LR_To_Multichannel_Output
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL FE_LR_To_Multichannel_Output
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FE_LR_To_Multichannel_Output.vhd VHDL PATH FE_LR_To_Multichannel_Output.vhd TOP_LEVEL_FILE

#
# module assignments
# 
set_module_assignment embeddedsw.dts.compatible dev,fe-LR-to-multichannel
set_module_assignment embeddedsw.dts.group LR-to-multichannel
set_module_assignment embeddedsw.dts.vendor fe

# 
# parameters
# 


# 
# display items
# 


# 
# connection point sys_clk
# 
add_interface sys_clk clock end
set_interface_property sys_clk clockRate 0
set_interface_property sys_clk ENABLED true
set_interface_property sys_clk EXPORT_OF ""
set_interface_property sys_clk PORT_NAME_MAP ""
set_interface_property sys_clk CMSIS_SVD_VARIABLES ""
set_interface_property sys_clk SVD_ADDRESS_GROUP ""

add_interface_port sys_clk sys_clk clk Input 1


# 
# connection point sys_reset
# 
add_interface sys_reset reset end
set_interface_property sys_reset associatedClock sys_clk
set_interface_property sys_reset synchronousEdges DEASSERT
set_interface_property sys_reset ENABLED true
set_interface_property sys_reset EXPORT_OF ""
set_interface_property sys_reset PORT_NAME_MAP ""
set_interface_property sys_reset CMSIS_SVD_VARIABLES ""
set_interface_property sys_reset SVD_ADDRESS_GROUP ""

add_interface_port sys_reset sys_reset reset_n Input 1


# 
# connection point data_in_left
# 
add_interface data_in_left avalon_streaming end
set_interface_property data_in_left associatedClock sys_clk
set_interface_property data_in_left associatedReset sys_reset
set_interface_property data_in_left dataBitsPerSymbol 8
set_interface_property data_in_left errorDescriptor ""
set_interface_property data_in_left firstSymbolInHighOrderBits true
set_interface_property data_in_left maxChannel 0
set_interface_property data_in_left readyLatency 0
set_interface_property data_in_left ENABLED true
set_interface_property data_in_left EXPORT_OF ""
set_interface_property data_in_left PORT_NAME_MAP ""
set_interface_property data_in_left CMSIS_SVD_VARIABLES ""
set_interface_property data_in_left SVD_ADDRESS_GROUP ""

add_interface_port data_in_left data_in_left_data data Input 32
add_interface_port data_in_left data_in_left_error error Input 2
add_interface_port data_in_left data_in_left_valid valid Input 1


# 
# connection point data_in_right
# 
add_interface data_in_right avalon_streaming end
set_interface_property data_in_right associatedClock sys_clk
set_interface_property data_in_right associatedReset sys_reset
set_interface_property data_in_right dataBitsPerSymbol 8
set_interface_property data_in_right errorDescriptor ""
set_interface_property data_in_right firstSymbolInHighOrderBits true
set_interface_property data_in_right maxChannel 0
set_interface_property data_in_right readyLatency 0
set_interface_property data_in_right ENABLED true
set_interface_property data_in_right EXPORT_OF ""
set_interface_property data_in_right PORT_NAME_MAP ""
set_interface_property data_in_right CMSIS_SVD_VARIABLES ""
set_interface_property data_in_right SVD_ADDRESS_GROUP ""

add_interface_port data_in_right data_in_right_data data Input 32
add_interface_port data_in_right data_in_right_error error Input 2
add_interface_port data_in_right data_in_right_valid valid Input 1


# 
# connection point multiplex_data_out
# 
add_interface multiplex_data_out avalon_streaming start
set_interface_property multiplex_data_out associatedClock sys_clk
set_interface_property multiplex_data_out associatedReset sys_reset
set_interface_property multiplex_data_out dataBitsPerSymbol 8
set_interface_property multiplex_data_out errorDescriptor ""
set_interface_property multiplex_data_out firstSymbolInHighOrderBits true
set_interface_property multiplex_data_out maxChannel 0
set_interface_property multiplex_data_out readyLatency 0
set_interface_property multiplex_data_out ENABLED true
set_interface_property multiplex_data_out EXPORT_OF ""
set_interface_property multiplex_data_out PORT_NAME_MAP ""
set_interface_property multiplex_data_out CMSIS_SVD_VARIABLES ""
set_interface_property multiplex_data_out SVD_ADDRESS_GROUP ""

add_interface_port multiplex_data_out multiplex_data_out_channel channel Output 2
add_interface_port multiplex_data_out multiplex_data_out_data data Output 32
add_interface_port multiplex_data_out multiplex_data_out_error error Output 2
add_interface_port multiplex_data_out multiplex_data_out_valid valid Output 1

