# TCL File Generated by Component Editor 18.0
# Thu Apr 09 12:50:50 MDT 2020
# DO NOT MODIFY


# 
# FE_AD4020 "FE_AD4020" v1.0
#  2020.04.09.12:50:50
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module FE_AD4020
# 
set_module_property DESCRIPTION ""
set_module_property NAME FE_AD4020
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "FPGA Open Speech Tools"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME FE_AD4020
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL FE_AD4020_v1
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FE_AD4020_v1.vhd VHDL PATH ../../component_library/AD4020/FE_AD4020_v1.vhd TOP_LEVEL_FILE
add_fileset_file spi_abstract.vhd VHDL PATH ../../component_library/spi/spi_abstract.vhd
add_fileset_file spi_commands.vhd VHDL PATH ../../component_library/spi/spi_commands.vhd
add_fileset_file spi_clk_delay.vhd VHDL PATH ../../component_library/spi/spi_clk_delay.vhd


# 
# parameters
# 
add_parameter input_clk_freq INTEGER 71000000
set_parameter_property input_clk_freq DEFAULT_VALUE 71000000
set_parameter_property input_clk_freq DISPLAY_NAME input_clk_freq
set_parameter_property input_clk_freq TYPE INTEGER
set_parameter_property input_clk_freq UNITS None
set_parameter_property input_clk_freq ALLOWED_RANGES -2147483648:2147483647
set_parameter_property input_clk_freq HDL_PARAMETER true


# 
# display items
# 


# 
# connection point Line_In
# 
add_interface Line_In avalon_streaming start
set_interface_property Line_In associatedClock sys_clock
set_interface_property Line_In associatedReset sys_reset
set_interface_property Line_In dataBitsPerSymbol 32
set_interface_property Line_In errorDescriptor ""
set_interface_property Line_In firstSymbolInHighOrderBits true
set_interface_property Line_In maxChannel 0
set_interface_property Line_In readyLatency 0
set_interface_property Line_In ENABLED true
set_interface_property Line_In EXPORT_OF ""
set_interface_property Line_In PORT_NAME_MAP ""
set_interface_property Line_In CMSIS_SVD_VARIABLES ""
set_interface_property Line_In SVD_ADDRESS_GROUP ""

add_interface_port Line_In AD4020_data_out data Output 32
add_interface_port Line_In AD4020_error_out error Output 2
add_interface_port Line_In AD4020_valid_out valid Output 1
add_interface_port Line_In AD4020_channel_out channel Output 2
set_interface_assignment Line_In channel 0


# 
# connection point connect_to_ad4020
# 
add_interface connect_to_ad4020 conduit end
set_interface_property connect_to_ad4020 associatedClock spi_clk
set_interface_property connect_to_ad4020 associatedReset sys_reset
set_interface_property connect_to_ad4020 ENABLED true
set_interface_property connect_to_ad4020 EXPORT_OF ""
set_interface_property connect_to_ad4020 PORT_NAME_MAP ""
set_interface_property connect_to_ad4020 CMSIS_SVD_VARIABLES ""
set_interface_property connect_to_ad4020 SVD_ADDRESS_GROUP ""

add_interface_port connect_to_ad4020 AD4020_CONV_out cnv Output 1
add_interface_port connect_to_ad4020 AD4020_MISO_in miso Input 1
add_interface_port connect_to_ad4020 AD4020_MOSI_out mosi Output 1
add_interface_port connect_to_ad4020 AD4020_SCLK_out sclk Output 1


# 
# connection point sys_reset
# 
add_interface sys_reset reset end
set_interface_property sys_reset associatedClock sys_clock
set_interface_property sys_reset synchronousEdges DEASSERT
set_interface_property sys_reset ENABLED true
set_interface_property sys_reset EXPORT_OF ""
set_interface_property sys_reset PORT_NAME_MAP ""
set_interface_property sys_reset CMSIS_SVD_VARIABLES ""
set_interface_property sys_reset SVD_ADDRESS_GROUP ""

add_interface_port sys_reset sys_reset_n reset_n Input 1


# 
# connection point sys_clock
# 
add_interface sys_clock clock end
set_interface_property sys_clock clockRate 0
set_interface_property sys_clock ENABLED true
set_interface_property sys_clock EXPORT_OF ""
set_interface_property sys_clock PORT_NAME_MAP ""
set_interface_property sys_clock CMSIS_SVD_VARIABLES ""
set_interface_property sys_clock SVD_ADDRESS_GROUP ""

add_interface_port sys_clock sys_clk clk Input 1


# 
# connection point spi_clk
# 
add_interface spi_clk clock end
set_interface_property spi_clk clockRate 0
set_interface_property spi_clk ENABLED true
set_interface_property spi_clk EXPORT_OF ""
set_interface_property spi_clk PORT_NAME_MAP ""
set_interface_property spi_clk CMSIS_SVD_VARIABLES ""
set_interface_property spi_clk SVD_ADDRESS_GROUP ""

add_interface_port spi_clk spi_clk clk Input 1

