-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\wickh\Documents\NIH\simulink_models\models\noise_suppression\hdlsrc\noise_suppression\noise_suppression_Reciprocal_nw_block.vhd
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: noise_suppression_Reciprocal_nw_block
-- Source Path: 
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY noise_suppression_Reciprocal_nw_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        in0                               :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En20
        out0                              :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En2
        );
END noise_suppression_Reciprocal_nw_block;


ARCHITECTURE rtl OF noise_suppression_Reciprocal_nw_block IS

  ATTRIBUTE multstyle : string;

  ATTRIBUTE multstyle OF rtl : ARCHITECTURE IS "dsp";

  -- Component Declarations
  COMPONENT noise_suppression_Reciprocal1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          recip_in                        :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En20
          recip_out                       :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En2
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : noise_suppression_Reciprocal1
    USE ENTITY work.noise_suppression_Reciprocal1(rtl);

  -- Signals
  SIGNAL Reciprocal1_out1                 : std_logic_vector(23 DOWNTO 0);  -- ufix24

BEGIN
  u_Reciprocal : noise_suppression_Reciprocal1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              recip_in => in0,  -- sfix24_En20
              recip_out => Reciprocal1_out1  -- sfix24_En2
              );

  out0 <= Reciprocal1_out1;

END rtl;

