# TCL File Generated by Component Editor 18.0
# Thu Feb 13 13:28:09 MST 2020
# DO NOT MODIFY


# 
# FE_Streaming_Counter "FE_Streaming_Counter" v1.0
#  2020.02.13.13:28:09
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module FE_Streaming_Counter
# 
set_module_property DESCRIPTION ""
set_module_property NAME FE_Streaming_Counter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME FE_Streaming_Counter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL FE_Streaming_Counter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FE_Streaming_Counter.vhd VHDL PATH FE_Streaming_Counter.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter n_channels INTEGER 8 ""
set_parameter_property n_channels DEFAULT_VALUE 8
set_parameter_property n_channels DISPLAY_NAME n_channels
set_parameter_property n_channels WIDTH ""
set_parameter_property n_channels TYPE INTEGER
set_parameter_property n_channels UNITS None
set_parameter_property n_channels ALLOWED_RANGES -2147483648:2147483647
set_parameter_property n_channels DESCRIPTION ""
set_parameter_property n_channels HDL_PARAMETER true
add_parameter channel_width INTEGER 8
set_parameter_property channel_width DEFAULT_VALUE 8
set_parameter_property channel_width DISPLAY_NAME channel_width
set_parameter_property channel_width TYPE INTEGER
set_parameter_property channel_width UNITS None
set_parameter_property channel_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property channel_width HDL_PARAMETER true
add_parameter data_width INTEGER 32
set_parameter_property data_width DEFAULT_VALUE 32
set_parameter_property data_width DISPLAY_NAME data_width
set_parameter_property data_width TYPE INTEGER
set_parameter_property data_width UNITS None
set_parameter_property data_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property data_width HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock sys_clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock sys_clk
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 32
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source data_output_channel channel Output channel_width
add_interface_port avalon_streaming_source data_output_data data Output data_width
add_interface_port avalon_streaming_source data_output_error error Output 2
add_interface_port avalon_streaming_source data_output_valid valid Output 1


# 
# connection point sys_clk
# 
add_interface sys_clk clock end
set_interface_property sys_clk clockRate 0
set_interface_property sys_clk ENABLED true
set_interface_property sys_clk EXPORT_OF ""
set_interface_property sys_clk PORT_NAME_MAP ""
set_interface_property sys_clk CMSIS_SVD_VARIABLES ""
set_interface_property sys_clk SVD_ADDRESS_GROUP ""

add_interface_port sys_clk sys_clk clk Input 1

